apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsenrcypt-prod
spec:
  acme:
    email: mafoki@inbox.ru
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: le-staging-pk
    solvers:
      - http01:
          ingress:
            class: nginx