---
apiVersion: v1
kind: Pod
metadata:
  name: v2app
  namespace: test
  labels:
    env: test
spec: 
  containers:
  - name: v2app-container
    image: docker.io/lifeoutro/applications:v2
---
apiVersion: v1
kind: Pod
metadata:
  name: v2app
  namespace: preprod
  labels:
    env: preprod
spec: 
  containers:
  - name: v2app-container
    image: docker.io/lifeoutro/applications:v2
---
apiVersion: v1
kind: Pod
metadata:
  name: v2app
  namespace: prod
  labels: 
    env: prod
spec: 
  containers:
  - name: v2app-container
    image: docker.io/lifeoutro/applications:v2
