
apiVersion: v1
kind: Service
metadata:
  name: srv-svc-v3
spec:
  selector:
    app: svc-pod-v3
  ports:
    - name: http
      port: 80
      targetPort: xhttp
    - name: https
      port: 443
      targetPort: xhttps  
  type: ClusterIP
---
apiVersion: v1
kind: Pod
metadata:
  name: svc-pod
  labels:
    app: svc-pod-v3
spec:
  containers:
  - name: svc-pod-cont-v3
    image: docker.io/lifeoutro/applications:v3
    ports:
      - name: xhttp
        containerPort: 80
      - name: xhttps
        containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: svc-pod2
  labels:
    app: svc-pod-v3
spec:
  containers:
  - name: svc-pod2-cont-v3
    image: docker.io/lifeoutro/applications:v3
    ports:
      - name: xhttp
        containerPort: 80
      - name: xhttps
        containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: svc-pod3
  labels:
    app: svc-pod-v3
spec:
  containers:
  - name: svc-pod3-cont-v3
    image: docker.io/lifeoutro/applications:v3
    ports:
      - name: xhttp
        containerPort: 80
      - name: xhttps
        containerPort: 80