apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-v2app
  namespace: test
spec:
  replicas: 2
  selector:
    app: v2applbl
  template:
    metadata:
      name: v2app
      namespace: test
      labels:
        app: v2applbl
    spec:
      containers:
        - name: v2app-container
          image: docker.io/lifeoutro/applications:v2          
          ports:
            - containerPort: 80
