apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-args-depl
spec:
  replicas: 2
  minReadySeconds: 15
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: app-args
  template:
    metadata:
      labels:
        app: app-args
    spec:
      containers:
      - name: app-args-container
        image: docker.io/lifeoutro/applications:v1.0-args
        command: [ "python3","-u","server.py" ]
        args: 
          - "3"
          - "2"
          - GPU
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: svc-app-args
spec:
  selector:
    app: app-args
  ports:
  - port: 80
    targetPort: 8000
    nodePort: 31111
  type: NodePort

