apiVersion: apps/v1
kind: Deployment
metadata:
  name: v5tcpdepl
spec:
  replicas: 1
  minReadySeconds: 15
  selector:
    matchLabels:
      app: v5tcp
  template:
    metadata:
      labels:
        app: v5tcp
    spec:
      containers:
      - name: v5tcp-container
        image: docker.io/lifeoutro/applications:v5
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
        livenessProbe:
          tcpSocket:
            port: 81
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: v5tcp-svc
spec:
  selector:
    app: v5tcp
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31112  #can specify port instead of allication automatically
  type: NodePort

