apiVersion: apps/v1
kind: Deployment
metadata:
  name: v5tcpdepl-host-headers
spec:
  replicas: 1
  minReadySeconds: 15
  selector:
    matchLabels:
      app: v5tcp-host-headers
  template:
    metadata:
      labels:
        app: v5tcp-host-headers
    spec:
      containers:
      - name: v5tcp-container
        image: docker.io/lifeoutro/applications:v5
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            httpHeaders:
            - name: Host
              value: kuber-healthy.example.com
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: v5tcp-host-headers-svc
spec:
  selector:
    app: v5tcp
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31112  #can specify port instead of allication automatically
  type: NodePort

