apiVersion: v1
kind: Service
metadata:
  name: manual-ep-svc
spec:
  ports:
  - port: 80
---
apiVersion: v1
kind: Endpoints
metadata:
  name: manual-ep-svc
subsets:
  - addresses:
    - ip: 172.17.0.10
    - ip: 172.17.0.6
    ports:
    - port: 80
