
apiVersion: v1
kind: Service
metadata:
  name: srv-svc0
spec:
  selector:
    app: svc-pod0
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Pod
metadata:
  name: svc-pod
  labels:
    app: svc-pod0
spec:
  containers:
  - name: svc-pod-cont0
    image: docker.io/lifeoutro/applications:v3
    ports:
      - name: http
        containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: svc-pod2
  labels:
    app: svc-pod0
spec:
  containers:
  - name: svc-pod2-cont0
    image: docker.io/lifeoutro/applications:v3
    ports:
      - name: http
        containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: svc-pod3
  labels:
    app: svc-pod0
spec:
  containers:
  - name: svc-pod3-cont0
    image: docker.io/lifeoutro/applications:v3
    ports:
      - name: http
        containerPort: 80