apiVersion: v1
kind: Service
metadata:
  name: svc-np
spec:
  #externalTrafficPolicy: Local
  sessionAffinity: ClientIP
  selector:
    app: v4app
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31111  #can specify port instead of allication automatically
  type: NodePort
